/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.sacola;

import controle.SacolaControle;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JToggleButton;

/**
 *
 * @author willr
 */
public class FormDetalhesSacola extends javax.swing.JFrame {
    
    private static final SacolaControle sacolaControle = new SacolaControle();

    /**
     * Creates new form FormDetalhesSacola
     */
    public FormDetalhesSacola() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblInfoConsultora = new javax.swing.JLabel();
        lblNomeConsultora = new javax.swing.JLabel();
        lblInfoDataAcerto = new javax.swing.JLabel();
        lblDataAcerto = new javax.swing.JLabel();
        lblInfoProdutos = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensDeSacola = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        btnFinalizar = new javax.swing.JToggleButton();
        btnFechar = new javax.swing.JToggleButton();
        lblInfoDataCriacao = new javax.swing.JLabel();
        lblDataCriacao = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblInfoConsultora1 = new javax.swing.JLabel();
        btnDevolver = new javax.swing.JButton();
        lblInfoValorTotal = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        btnGerarTermo = new javax.swing.JButton();
        btnAjuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalhes da Sacola");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setText("Detalhes da Sacola");

        lblInfoConsultora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInfoConsultora.setText("Nome da Consultora:");

        lblNomeConsultora.setText("Nome");

        lblInfoDataAcerto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInfoDataAcerto.setText("Data de Acerto:");

        lblDataAcerto.setText("Data");

        lblInfoProdutos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInfoProdutos.setText("Lista de Produtos:");

        tblItensDeSacola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Item", "Descrição", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItensDeSacola);

        btnFinalizar.setBackground(new java.awt.Color(0, 153, 102));
        btnFinalizar.setText("Finalizar Sacola");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnFechar.setBackground(new java.awt.Color(255, 102, 102));
        btnFechar.setText("Fechar");

        lblInfoDataCriacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInfoDataCriacao.setText("Data de Criação:");

        lblDataCriacao.setText("Data");

        lblCodigo.setText("Código");

        lblInfoConsultora1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInfoConsultora1.setText("Código:");

        btnDevolver.setBackground(new java.awt.Color(153, 204, 255));
        btnDevolver.setText("Devolver Produto");

        lblInfoValorTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInfoValorTotal.setText("Valor total:");

        lblValorTotal.setText("Valor");

        btnGerarTermo.setBackground(new java.awt.Color(153, 204, 255));
        btnGerarTermo.setText("Gerar Termo de Ciência");

        btnAjuda.setBackground(new java.awt.Color(255, 204, 0));
        btnAjuda.setText("Ajuda?");
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAjuda))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfoProdutos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFinalizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDevolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFechar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInfoConsultora1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCodigo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInfoDataAcerto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataAcerto))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblInfoDataCriacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataCriacao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInfoConsultora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNomeConsultora))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInfoValorTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValorTotal))
                            .addComponent(btnGerarTermo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnAjuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(lblInfoConsultora1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoConsultora)
                    .addComponent(lblNomeConsultora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataCriacao)
                    .addComponent(lblInfoDataCriacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoDataAcerto)
                    .addComponent(lblDataAcerto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoValorTotal)
                    .addComponent(lblValorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerarTermo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(btnDevolver)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
//      finalizada
        Integer id = Integer.parseInt(lblCodigo.getText());
        sacolaControle.finalizar(id);

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://github.com/luisfrsa/ISS_Atelie/tree/master/ajuda#detalhes-da-sacola"));
        } catch (URISyntaxException ex) {
            System.out.println("Erro: " + ex.getMessage());
        } catch (IOException ex) {
            System.out.println("Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDetalhesSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDetalhesSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDetalhesSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDetalhesSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDetalhesSacola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjuda;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JToggleButton btnFechar;
    private javax.swing.JToggleButton btnFinalizar;
    private javax.swing.JButton btnGerarTermo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataAcerto;
    private javax.swing.JLabel lblDataCriacao;
    private javax.swing.JLabel lblInfoConsultora;
    private javax.swing.JLabel lblInfoConsultora1;
    private javax.swing.JLabel lblInfoDataAcerto;
    private javax.swing.JLabel lblInfoDataCriacao;
    private javax.swing.JLabel lblInfoProdutos;
    private javax.swing.JLabel lblInfoValorTotal;
    private javax.swing.JLabel lblNomeConsultora;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTable tblItensDeSacola;
    // End of variables declaration//GEN-END:variables

    public JToggleButton getBtnFechar() {
        return btnFechar;
    }
    
    public JToggleButton getBtnFinalizar() {
        return btnFinalizar;
    }
    
    public JLabel getLblNomeConsultora() {
        return lblNomeConsultora;
    }
    
    public JTable getTblItensDeSacola() {
        return tblItensDeSacola;
    }
    
    public JLabel getLblDataAcerto() {
        return lblDataAcerto;
    }
    
    public JLabel getLblDataCriacao() {
        return lblDataCriacao;
    }
    
    public JLabel getLblCodigo() {
        return lblCodigo;
    }

    public JButton getBtnDevolver() {
        return btnDevolver;
    }

    public JButton getBtnGerarTermo() {
        return btnGerarTermo;
    }

    public JLabel getLblValorTotal() {
        return lblValorTotal;
    }
    
    
}
