/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.sacola;

import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JToggleButton;

/**
 *
 * @author willr
 */
public class FormDetalhesSacola extends javax.swing.JFrame {

    /**
     * Creates new form FormDetalhesSacola
     */
    public FormDetalhesSacola() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblInfoConsultora = new javax.swing.JLabel();
        lblNomeConsultora = new javax.swing.JLabel();
        lblInfoDataAcerto = new javax.swing.JLabel();
        lblDataAcerto = new javax.swing.JLabel();
        lblInfoProdutos = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensDeSacola = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        btnFinalizar = new javax.swing.JToggleButton();
        btnFechar = new javax.swing.JToggleButton();
        lblInfoDataCriacao = new javax.swing.JLabel();
        lblDataCriacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalhes da Sacola");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setText("Detalhes da Sacola");

        lblInfoConsultora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInfoConsultora.setText("Nome da Consultora:");

        lblNomeConsultora.setText("Nome");

        lblInfoDataAcerto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInfoDataAcerto.setText("Data de Acerto:");

        lblDataAcerto.setText("Data");

        lblInfoProdutos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInfoProdutos.setText("Lista de Produtos:");

        tblItensDeSacola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItensDeSacola);

        btnFinalizar.setBackground(new java.awt.Color(153, 204, 255));
        btnFinalizar.setText("Finalizar Sacola");

        btnFechar.setBackground(new java.awt.Color(255, 102, 102));
        btnFechar.setText("Fechar");

        lblInfoDataCriacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInfoDataCriacao.setText("Data de Criação:");

        lblDataCriacao.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTitulo)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblInfoConsultora)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblNomeConsultora))
                        .addComponent(lblInfoProdutos)
                        .addComponent(jSeparator2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnFinalizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                            .addComponent(btnFechar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfoDataAcerto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDataAcerto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfoDataCriacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDataCriacao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoConsultora)
                    .addComponent(lblNomeConsultora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoDataCriacao)
                    .addComponent(lblDataCriacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataAcerto)
                    .addComponent(lblInfoDataAcerto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDetalhesSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDetalhesSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDetalhesSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDetalhesSacola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDetalhesSacola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnFechar;
    private javax.swing.JToggleButton btnFinalizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblDataAcerto;
    private javax.swing.JLabel lblDataCriacao;
    private javax.swing.JLabel lblInfoConsultora;
    private javax.swing.JLabel lblInfoDataAcerto;
    private javax.swing.JLabel lblInfoDataCriacao;
    private javax.swing.JLabel lblInfoProdutos;
    private javax.swing.JLabel lblNomeConsultora;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblItensDeSacola;
    // End of variables declaration//GEN-END:variables

    
    public JToggleButton getBtnFechar() {
        return btnFechar;
    }

    public JToggleButton getBtnFinalizar() {
        return btnFinalizar;
    }

    public JLabel getLblNomeConsultora() {
        return lblNomeConsultora;
    }

    public JTable getTblItensDeSacola() {
        return tblItensDeSacola;
    }

    public JLabel getLblDataAcerto() {
        return lblDataAcerto;
    }

    public JLabel getLblDataCriacao() {
        return lblDataCriacao;
    }

}
