/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.login;

import java.awt.Point;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author willr
 */
public class FormLogin2 extends javax.swing.JFrame {
    
    private static Point point = new Point();

    /**
     * Creates new form FormLogin2
     */
    public FormLogin2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechar = new javax.swing.JLabel();
        btnAcessar = new javax.swing.JLabel();
        jButtonRecuperaSenha = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordSenha = new javax.swing.JPasswordField();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ateliê Doce Beleza");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar.fw.png"))); // NOI18N
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFecharMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblFecharMouseReleased(evt);
            }
        });
        getContentPane().add(lblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        btnAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao Acessar1.fw.png"))); // NOI18N
        btnAcessar.setText("jLabel1");
        btnAcessar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcessarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcessarMouseExited(evt);
            }
        });
        getContentPane().add(btnAcessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 130, 70));

        jButtonRecuperaSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao Recuperar1.fw.png"))); // NOI18N
        jButtonRecuperaSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRecuperaSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRecuperaSenhaMouseExited(evt);
            }
        });
        getContentPane().add(jButtonRecuperaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 200, 70));

        jTextFieldUsuario.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(81, 27, 98));
        jTextFieldUsuario.setBorder(null);
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 300, 50));

        jPasswordSenha.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jPasswordSenha.setForeground(new java.awt.Color(81, 27, 98));
        jPasswordSenha.setBorder(null);
        getContentPane().add(jPasswordSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 300, 50));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo Tela Login.fw.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseEntered
        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar2.fw.png")));
    }//GEN-LAST:event_lblFecharMouseEntered

    private void lblFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseExited
        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-fechar.fw.png")));
    }//GEN-LAST:event_lblFecharMouseExited

    private void lblFecharMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseReleased
        dispose();
    }//GEN-LAST:event_lblFecharMouseReleased

    private void btnAcessarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcessarMouseEntered
        btnAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao Acessar2.fw.png")));
    }//GEN-LAST:event_btnAcessarMouseEntered

    private void btnAcessarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcessarMouseExited
        btnAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao Acessar1.fw.png")));
    }//GEN-LAST:event_btnAcessarMouseExited

    private void jButtonRecuperaSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRecuperaSenhaMouseEntered
        jButtonRecuperaSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao Recuperar1.fw.png")));
    }//GEN-LAST:event_jButtonRecuperaSenhaMouseEntered

    private void jButtonRecuperaSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRecuperaSenhaMouseExited
        jButtonRecuperaSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Botao Recuperar2.fw.png")));
    }//GEN-LAST:event_jButtonRecuperaSenhaMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAcessar;
    private javax.swing.JLabel jButtonRecuperaSenha;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblFundo;
    // End of variables declaration//GEN-END:variables

    public JLabel getBtnAcessar() {
        return btnAcessar;
    }

    public JLabel getjButtonRecuperaSenha() {
        return jButtonRecuperaSenha;
    }

    public JTextField getjPasswordSenha() {
        return jPasswordSenha;
    }

    public JTextField getjTextFieldUsuario() {
        return jTextFieldUsuario;
    }


}
